title: L'Hêtre à La Loupe
description: Documentaires radiophoniques
author: Paul Bureau & Corentin Mançois
email: hetrealaloupe@protonmail.com
lang: fr
copyright: "&#x2117; &amp; &#xA9; 2020"
logo: /assets/img/logo.png
# baseurl: "" # the subpath of your site, e.g. /blog
url: http://hetrealaloupe.fr/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
