title: L'hêtre à la Loupe
description: Documentaires radiophoniques / Hetrealaloupe@protonmail.com
author: Paul Bureau et Corentin Mançois
email: hetrealaloupe@protonmail.com
lang: fr
copyright: "&#x2117; &amp; &#xA9; 2022"
logo: /assets/img/HALL.jpg
# baseurl: "" # the subpath of your site, e.g. /blog

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
